#!/bin/bash

# Copyright (C) 2018 Massachusetts Institute of Technology.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'This script must be run as root' >&2
  exit 1
fi

apt-get update -qq
apt-get install --no-install-recommends \
  cmake \
  curl \
  doxygen \
  freeglut3-dev \
  g++ \
  gcc \
  libglib2.0-dev \
  libgtk2.0-dev \
  libjpeg8-dev \
  libpng12-dev \
  libxmu-dev \
  make \
  openjdk-7-jdk \
  pkg-config \
  python-dev \
  python-gtk2 \
  python-numpy \
  python-scipy \
  python3-dev \
  python3-numpy \
  python3-scipy \
  zlib1g-dev

# TODO: Install a compatible version of LCM.

pushd /tmp
curl -O https://cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz
trap 'rm -f cmake-3.5.1-Linux-x86_64.tar.gz' EXIT
echo 'e8f94a57a95c6a4cbe0fe05b5d16a7b78bf67c77fcec14f0834303a06a6244b0  cmake-3.5.1-Linux-x86_64.tar.gz' | sha256sum -c
tar -xzf cmake-3.5.1-Linux-x86_64.tar.gz
trap 'rm -rf cmake-3.5.1-Linux-x86_64' EXIT
cp -R cmake-3.5.1-Linux-x86_64 /opt/cmake
popd
