#!/bin/bash

# Copyright (C) 2018 Massachusetts Institute of Technology.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'This script must be run as root' >&2
  exit 1
fi

apt-get update -qq
apt-get install --no-install-recommends lsb-release

if [[ "$(lsb_release -sc)" != 'xenial' ]]; then
  echo 'This script requires Ubuntu 16.04 (Xenial)' >&2
  exit 2
fi

apt-get install --no-install-recommends \
  doxygen \
  dpkg-dev \
  file \
  freeglut3-dev \
  g++ \
  gcc \
  git \
  libglib2.0-dev \
  libgtk2.0-dev \
  libjpeg8-dev \
  libpng12-dev \
  libxmu-dev \
  make \
  openjdk-8-jdk \
  pkg-config \
  python-dev \
  python-gtk2 \
  python-numpy \
  python-scipy \
  python3-dev \
  python3-numpy \
  python3-scipy \
  wget \
  zlib1g-dev

wget https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.sh && \
  chmod +x cmake-3.11.2-Linux-x86_64.sh && \
  ./cmake-3.11.2-Linux-x86_64.sh --skip-license --prefix /

# TODO: Install a compatible version of LCM.
