#!/bin/bash

# Copyright (C) 2018 Massachusetts Institute of Technology.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'This script must be run as root' >&2
  exit 1
fi

apt-get update -qq
apt-get install --no-install-recommends lsb-release

if [[ "$(lsb_release -sc)" != 'xenial' ]]; then
  echo 'This script requires Ubuntu 16.04 (Xenial)' >&2
  exit 2
fi

apt-get install --no-install-recommends \
  apt-transport-https \
  build-essential \
  ca-certificates \
  default-jdk \
  doxygen \
  file \
  freeglut3-dev \
  git \
  gnupg \
  gnupg-curl \
  libglib2.0-dev \
  libgtk2.0-dev \
  libjpeg8-dev \
  libpng12-dev \
  libxmu-dev \
  pkg-config \
  python-dev \
  python-gtk2 \
  python-numpy \
  python-scipy \
  python3-dev \
  python3-numpy \
  python3-scipy \
  zlib1g-dev

apt-key adv --fetch-keys https://apt.kitware.com/keys/kitware-archive-latest.asc
echo 'deb https://apt.kitware.com/ubuntu/ xenial main' | tee /etc/apt/sources.list.d/kitware.list

apt-get update -qq
apt-get install --no-install-recommends cmake

# TODO: Install a compatible version of LCM.
