# -*- mode: ruby -*-
# vi: set ft=ruby :

brew 'cmake'
brew 'doxygen'
brew 'glib'
brew 'gtk+3'
brew 'jpeg'
brew 'lcm'
brew 'libpng'
brew 'numpy'
brew 'pkg-config'
brew 'pygobject3'
brew 'python'
brew 'scipy'

cask 'adoptopenjdk' unless system '/usr/libexec/java_home --failfast &> /dev/null'
cask 'xquartz' unless File.exist? '/opt/X11/include/X11/Xlib.h'
