# -*- mode: ruby -*-
# vim: set filetype=ruby :

# This file is part of libbot2.
#
# libbot2 is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# libbot2 is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with libbot2. If not, see <https://www.gnu.org/licenses/>.

brew 'cmake'
brew 'doxygen'
brew 'glib'
brew 'gtk+3'
brew 'jpeg'
brew 'lcm'
brew 'libpng'
brew 'numpy'
brew 'pkg-config'
brew 'pygobject3'
brew 'python'
brew 'scipy'

cask 'adoptopenjdk' unless system '/usr/libexec/java_home --failfast &> /dev/null'
cask 'xquartz' unless File.exist? '/opt/X11/include/X11/Xlib.h'
