# This file is part of libbot2.
#
# libbot2 is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# libbot2 is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with libbot2. If not, see <https://www.gnu.org/licenses/>.

---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - drake

  schedule:
    - cron: '0 6 * * *'

jobs:
  ubuntu-1804:
    name: Ubuntu 18.04 Bionic
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: Install Git
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get autoremove -qq
          apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
              --no-install-recommends install \
            ca-certificates \
            git
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          ./scripts/setup/linux/ubuntu/bionic/install_prereqs
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: Build
        run: |
          ./scripts/package/linux/ubuntu/common/build.sh
        shell: bash

  ubuntu-2004:
    name: Ubuntu 20.04 Focal
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Install Git
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get autoremove -qq
          apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
              --no-install-recommends install \
            ca-certificates \
            git
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          ./scripts/setup/linux/ubuntu/focal/install_prereqs
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: Build
        run: |
          ./scripts/package/linux/ubuntu/common/build.sh
        shell: bash

  ubuntu-2204:
    name: Ubuntu 22.04 Jammy
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Install Git
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get autoremove -qq
          apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
              --no-install-recommends install \
            ca-certificates \
            git
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          ./scripts/setup/linux/ubuntu/jammy/install_prereqs
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: Build
        run: |
          ./scripts/package/linux/ubuntu/common/build.sh
        shell: bash
